const rawEmployeesData = [
  {
    "id": 20114,
    "name": "ابراهيم احمد حمد مرير",
    "national_id": 1054638174,
    "phone": 538216117,
    "correspondence": "ibahmarir",
    "email": "imrir@momah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 20115,
    "name": "ابراهيم بيشي احمد سعيد حيدر",
    "national_id": 1054182397,
    "phone": 509803975,
    "correspondence": "ibbehedar",
    "email": "ihayder@momah.gov.sa",
    "job_title": "مساعد ادارى",
    "department": "المشاريع والصحة العامة",
    "section": "الطرق",
    "unit": ""
  },
  {
    "id": 20116,
    "name": "ابراهيم حسين إبراهيم شيبة",
    "national_id": 1016408336,
    "phone": 509782838,
    "correspondence": "ibheshebah",
    "email": "ishaiba@momah.gov.sa",
    "job_title": "مراقب انشاءات",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 20120,
    "name": "ابراهيم محمد إبراهيم جعفري",
    "national_id": 1024086082,
    "phone": 564400393,
    "correspondence": "ibmojaeifri",
    "email": "ijafari@momah.gov.sa",
    "job_title": "مدقق حسابات",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201254,
    "name": "ابراهيم محمد بوكر عثمان",
    "national_id": 1042456820,
    "phone": 567991905,
    "correspondence": "ibmoothman",
    "email": "iosman@momah.gov.sa",
    "job_title": "كهربائى",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 20121,
    "name": "ابراهيم محمد حسن سلطان",
    "national_id": 1076628534,
    "phone": 538216117,
    "correspondence": "ibmosoltan",
    "email": "isultan@momah.gov.sa",
    "job_title": "سائق معدات ثقيله",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 20122,
    "name": "ابراهيم محمد قاسم سيد",
    "national_id": 1076246857,
    "phone": 502400012,
    "correspondence": "ibmosaid",
    "email": "imsayed@momah.gov.sa",
    "job_title": "كاتب",
    "department": "الشؤون القانونية",
    "section": "المرافعات",
    "unit": ""
  },
  {
    "id": 20123,
    "name": "ابراهيم موسى حسين حداد",
    "national_id": 1072213547,
    "phone": 560099985,
    "correspondence": "ibmohdad",
    "email": "ihadad@momah.gov.sa",
    "job_title": "مشرف أسواق",
    "department": "الموارد البشرية",
    "section": "الإمن والسلامة",
    "unit": ""
  },
  {
    "id": 5061,
    "name": "ابوبكر رياض ابوبكر باصهي",
    "national_id": 1072387713,
    "phone": 550942219,
    "correspondence": "abribasahi",
    "email": "arbasahi@momah.gov.sa",
    "job_title": "مهندس مدني",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 20124,
    "name": "احمد إبراهيم حسن ظافر النعمي",
    "national_id": 1024754374,
    "phone": 557795556,
    "correspondence": "ahibdaphir",
    "email": "aalnami@momah.gov.sa",
    "job_title": "مسجل معلومات",
    "department": "الموارد البشرية",
    "section": "الموارد البشرية",
    "unit": ""
  },
  {
    "id": 20125,
    "name": "احمد إبراهيم محمد أبوعيشه",
    "national_id": 1069789715,
    "phone": 557176177,
    "correspondence": "ahibabuishah",
    "email": "aabuaisha@momah.gov.sa",
    "job_title": "مراقب خدمات",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20207,
    "name": "احمد بن علي بن حسن مجرشي",
    "national_id": 1069388021,
    "phone": 502071528,
    "correspondence": "ahalmgreshy",
    "email": "azelaey@momah.gov.sa",
    "job_title": "رئيس مراقبين صحيين",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "unit": ""
  },
  {
    "id": 2012,
    "name": "احمد جبريل محمد عسيري",
    "national_id": 1049187063,
    "phone": 502320884,
    "correspondence": "ahjeaseri",
    "email": "agaseeri@momah.gov.sa",
    "job_title": "مراقب انشاءات",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 201281,
    "name": "احمد جمعان حامد ال محمد",
    "national_id": 1034590867,
    "phone": 500452948,
    "correspondence": "ahjaalmohmed",
    "email": "agmohammed@momah.gov.sa",
    "job_title": "كهربائى",
    "department": "المشاريع والصحة العامة",
    "section": "النظافة",
    "unit": ""
  },
  {
    "id": 2013,
    "name": "احمد حسن عبده ايوب",
    "national_id": 1076542842,
    "phone": 568128424,
    "correspondence": "ahhaayob",
    "email": "aayoub@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 20126,
    "name": "احمد حسين يحيى مشلوي",
    "national_id": 1085201786,
    "phone": 531988066,
    "correspondence": "ahhemeshalwi",
    "email": "amashlawi@momah.gov.sa",
    "job_title": "مراقب عمال",
    "department": "المشاريع والصحة العامة",
    "section": "المرافق العامة",
    "unit": ""
  },
  {
    "id": 20127,
    "name": "احمد عبدالله أحمد قصادي",
    "national_id": 1069412029,
    "phone": 556180987,
    "correspondence": "ahabqosady",
    "email": "aqusadi@momah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "المشاريع والصحة العامة",
    "section": "النظافة",
    "unit": ""
  },
  {
    "id": 201263,
    "name": "احمد عبده علي أبو شرين",
    "national_id": 1081434399,
    "phone": 556739347,
    "correspondence": "ahababushireen",
    "email": "aabushrain@momah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "المشاريع والصحة العامة",
    "section": "الصحة العامة",
    "unit": ""
  },
  {
    "id": 201256,
    "name": "احمد عبده محمد غزاوي",
    "national_id": 1071984742,
    "phone": 503014401,
    "correspondence": "ahabgazwi",
    "email": "agazawi@momah.gov.sa",
    "job_title": "اخصائي تقنية هندسة كهرباء ممارس",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع والصحة العامة",
    "unit": ""
  },
  {
    "id": 201280,
    "name": "احمد علي صالح شافعي",
    "national_id": 1019158946,
    "phone": 502410546,
    "correspondence": "ahalshafiei",
    "email": "ashafie@momah.gov.sa",
    "job_title": "مراقب صحى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 2015,
    "name": "احمد علي يحيى عماري",
    "national_id": 1080544594,
    "phone": 538216117,
    "correspondence": "ahalamari",
    "email": "aammary@momah.gov.sa",
    "job_title": "كاتب",
    "department": "المشاريع والصحة العامة",
    "section": "صيانة الحدائق",
    "unit": ""
  },
  {
    "id": 2016,
    "name": "احمد عوض احمد باصهي",
    "national_id": 1028139903,
    "phone": 504149926,
    "correspondence": "ahawbasahi",
    "email": "abasahi@momah.gov.sa",
    "job_title": "أمين مستودع",
    "department": "الشؤون المالية",
    "section": "المستودعات",
    "unit": ""
  },
  {
    "id": 20129,
    "name": "احمد محمد بشير العبسي",
    "national_id": 1013988660,
    "phone": 538771557,
    "correspondence": "ahmoalabsi",
    "email": "aalabsy@momah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 20130,
    "name": "احمد محمد بن محمد حكمي",
    "national_id": 1067984193,
    "phone": 532259796,
    "correspondence": "ahmohakmi",
    "email": "amhakamy@momah.gov.sa",
    "job_title": "كاتب",
    "department": "التخطيط العمراني والأراضي",
    "section": "نزع الملكية",
    "unit": ""
  },
  {
    "id": 2018,
    "name": "احمد محمد علي الذروي",
    "national_id": 1075939056,
    "phone": 538216117,
    "correspondence": "ahmoalthrwi",
    "email": "aaltherwii@momah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "المشاريع والصحة العامة",
    "section": "الكوارث والعمليات",
    "unit": ""
  },
  {
    "id": 20131,
    "name": "احمد مكين محمد معافا",
    "national_id": 1051382115,
    "phone": 508513635,
    "correspondence": "ahmkmoafa",
    "email": "ammaafa@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "المشاريع والصحة العامة",
    "section": "صيانة الانارة",
    "unit": ""
  },
  {
    "id": 20132,
    "name": "احمد مهدي عيسى عاطفي",
    "national_id": 1023147208,
    "phone": 566667826,
    "correspondence": "ahmaattafy",
    "email": "aatify@momah.gov.sa",
    "job_title": "كاتب",
    "department": "المشاريع والصحة العامة",
    "section": "النظافة",
    "unit": ""
  },
  {
    "id": 20216,
    "name": "احمد ناصر حسن شبيلي",
    "national_id": 1097311193,
    "phone": 531904476,
    "correspondence": "ahnashbaily",
    "email": "anshbili@momah.gov.sa",
    "job_title": "مهندس معماري محترف أول",
    "department": "التخطيط العمراني والأراضي",
    "section": "التخطيط العمراني والأراضي",
    "unit": ""
  },
  {
    "id": 20134,
    "name": "احمد ناصر هادي الذروي",
    "national_id": 1098083858,
    "phone": 569959956,
    "correspondence": "ahnaaltherwi",
    "email": "aalzerwi@momah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "الموارد البشرية",
    "section": "الإتصالات الإدارية",
    "unit": ""
  },
  {
    "id": 201251,
    "name": "احمد هادي علي عنبري",
    "national_id": 1044946760,
    "phone": 538216117,
    "correspondence": "ahhaanbari",
    "email": "aanbari@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 5045,
    "name": "احمد هادي عيسى جعامي",
    "national_id": 1085983995,
    "phone": 549096663,
    "correspondence": "ahhajaami",
    "email": "",
    "job_title": "مستخدم",
    "department": "مكتب رئيس البلدية",
    "section": "مكتب رئيس اليلدية",
    "unit": ""
  },
  {
    "id": 20135,
    "name": "احمد هادي محمد نش",
    "national_id": 1057062174,
    "phone": 554321232,
    "correspondence": "ahhanash",
    "email": "ansh@momah.gov.sa",
    "job_title": "اخصائي عمليات موارد بشرية",
    "department": "الشؤون القانونية",
    "section": "الشؤون القانونية",
    "unit": ""
  },
  {
    "id": 2019,
    "name": "احمد يحيى حسين صديق معافا",
    "national_id": 1055894636,
    "phone": 538216117,
    "correspondence": "ahyamoafa",
    "email": "asiddiqi@momah.gov.sa",
    "job_title": "كهربائى",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 2050,
    "name": "اسامه بن عمر علي السلامي",
    "national_id": 1055687352,
    "phone": 599384554,
    "correspondence": "osomalsailmy",
    "email": "",
    "job_title": "بند الأجور",
    "department": "التخطيط العمراني والأراضي",
    "section": "نزع الملكية",
    "unit": ""
  },
  {
    "id": 2027,
    "name": "الحسن ابن جده علي جوبحي",
    "national_id": 1113647729,
    "phone": 553232601,
    "correspondence": "albijobhi",
    "email": "agobahii@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "مكتب رئيس البلدية",
    "section": "مكتب رئيس اليلدية",
    "unit": ""
  },
  {
    "id": 20110,
    "name": "الحسن محمد أحمد طامي",
    "national_id": 1033669886,
    "phone": 555771972,
    "correspondence": "almotami",
    "email": "atamyr@momah.gov.sa",
    "job_title": "فنى زراعى مشرف",
    "department": "المشاريع والصحة العامة",
    "section": "صيانة الحدائق",
    "unit": ""
  },
  {
    "id": 20111,
    "name": "الحسن محمد حسن خطار",
    "national_id": 1057668913,
    "phone": 507764048,
    "correspondence": "almokhtar",
    "email": "akhatar@momah.gov.sa",
    "job_title": "مراقب انشاءات",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 5038,
    "name": "المحسن حسن الحسن النعمي",
    "national_id": 1042461531,
    "phone": 501118278,
    "correspondence": "",
    "email": "mmneami@momah.gov.sa",
    "job_title": "مساعد اداري",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 20112,
    "name": "المعتز بالله عبده موسى عقيلي",
    "national_id": 1106142795,
    "phone": 551771179,
    "correspondence": "albeaqili",
    "email": "amaqili@momah.gov.sa",
    "job_title": "كاتب",
    "department": "الموارد البشرية",
    "section": "الإتصالات الإدارية",
    "unit": ""
  },
  {
    "id": 2021,
    "name": "امنه أحمد علي هارب رياني",
    "national_id": 1040093286,
    "phone": 509472212,
    "correspondence": "amahriyani",
    "email": "arayani@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20137,
    "name": "امين محمد حمود الحازمي",
    "national_id": 1058493295,
    "phone": 555779303,
    "correspondence": "ammoalhazmi",
    "email": "aalhazimy@momah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20113,
    "name": "انعام عبده عبودي حمراني",
    "national_id": 1118337276,
    "phone": 549221255,
    "correspondence": "anabhomrani",
    "email": "ahamrani@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "العلاقات العامة والمشاركة المجتمعية",
    "section": "العلاقات العامة والمشاركة المجتمعية",
    "unit": ""
  },
  {
    "id": 20138,
    "name": "انور احمد محمد باصهي",
    "national_id": 1037523485,
    "phone": 508877078,
    "correspondence": "anahbashiri",
    "email": "abasahy@momah.gov.sa",
    "job_title": "مسجل معلومات",
    "department": "المراجعة الداخلية",
    "section": "المراجعة والإلتزام",
    "unit": ""
  },
  {
    "id": 20139,
    "name": "انور جبريل معبر عبدالله",
    "national_id": 1068265980,
    "phone": 566990092,
    "correspondence": "amaabr",
    "email": "amaabri@momah.gov.sa",
    "job_title": "مراقب تعديات",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 5009,
    "name": "ايمن احمد عبدالله علي",
    "national_id": 1094680764,
    "phone": 534740084,
    "correspondence": "ayahali",
    "email": "aaali@momah.gov.sa",
    "job_title": "مساعد ادارى",
    "department": "المراجعة الداخلية",
    "section": "المراجعة والإلتزام",
    "unit": ""
  },
  {
    "id": 20140,
    "name": "بسام ناصر احمد شبعاني",
    "national_id": 1027409729,
    "phone": 508777581,
    "correspondence": "banashabani",
    "email": "bshaani@momah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "المشاريع والصحة العامة",
    "section": "صيانة الانارة",
    "unit": ""
  },
  {
    "id": 20142,
    "name": "بندر محمد موسى معافا",
    "national_id": 1070277122,
    "phone": 501854145,
    "correspondence": "bamomaafa",
    "email": "bmaafa@momah.gov.sa",
    "job_title": "مسجل معلومات",
    "department": "التخطيط العمراني والأراضي",
    "section": "الإراضي والتعديات",
    "unit": ""
  },
  {
    "id": 20143,
    "name": "بندر ناصر عبده غزاوي",
    "national_id": 1057246850,
    "phone": 569988623,
    "correspondence": "banagazwi",
    "email": "bgazawi@momah.gov.sa",
    "job_title": "مراقب ايرادات مشرف",
    "department": "التخصيص والإستدامة المالية",
    "section": "الفرص الإستثمارية",
    "unit": ""
  },
  {
    "id": 201252,
    "name": "بندر يحيى عزالدين خواجي",
    "national_id": 1077470670,
    "phone": 500841469,
    "correspondence": "bayakhawaji",
    "email": "bkhawagi@momah.gov.sa",
    "job_title": "مراقب خدمات",
    "department": "الشؤون المالية",
    "section": "المستودعات",
    "unit": ""
  },
  {
    "id": 20145,
    "name": "جابر محمد صديق كدان",
    "national_id": 1057325746,
    "phone": 553133291,
    "correspondence": "jamokadan",
    "email": "gkdan@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 20146,
    "name": "جلال رزق جهوي الشنتان",
    "national_id": 1021175508,
    "phone": 550343206,
    "correspondence": "jarialshentan",
    "email": "gshantan@momah.gov.sa",
    "job_title": "رئيس مراقبين صحيين",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20147,
    "name": "حامد احمد محمد البر",
    "national_id": 1052628995,
    "phone": 559397292,
    "correspondence": "haahalbr",
    "email": "halbar@momah.gov.sa",
    "job_title": "مراقب خدمات",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 5014,
    "name": "حسن رباع أبكر صديق",
    "national_id": 1079908511,
    "phone": 538216117,
    "correspondence": "hrasedieq",
    "email": "hsidiq@momah.gov.sa",
    "job_title": "مساعد حسابات مساعد",
    "department": "الشؤون المالية",
    "section": "المالية والميزانية",
    "unit": ""
  },
  {
    "id": 20148,
    "name": "حسن عبدالله علي جميمي",
    "national_id": 1072915562,
    "phone": 538216117,
    "correspondence": "haabjmemi",
    "email": "hgamimi@momah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20149,
    "name": "حسن محمد جابر سعد",
    "national_id": 1058265735,
    "phone": 533695035,
    "correspondence": "hamosaad",
    "email": "hsaad@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "المشاريع والصحة العامة",
    "section": "الصحة العامة",
    "unit": ""
  },
  {
    "id": 20151,
    "name": "حسن يحيى حسين النعمي",
    "national_id": 1041363712,
    "phone": 551659660,
    "correspondence": "hnyaalnaami",
    "email": "hyalnaami@momah.gov.sa",
    "job_title": "مأمور مشتريات",
    "department": "التخصيص والإستدامة المالية",
    "section": "الفرص الإستثمارية",
    "unit": ""
  },
  {
    "id": 20153,
    "name": "حسين عبدالله محمد زابط حطبي",
    "national_id": 1062729650,
    "phone": 538216117,
    "correspondence": "huabhatbi",
    "email": "hhatabi@momah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 20155,
    "name": "حسين محمد الزاهد حيدرالنعمي",
    "national_id": 1050525276,
    "phone": 533723288,
    "correspondence": "humoalnami",
    "email": "halzahed@momah.gov.sa",
    "job_title": "مصمم برامج",
    "department": "التحول الرقمي",
    "section": "التحول الرقمي",
    "unit": ""
  },
  {
    "id": 20156,
    "name": "حسين محمد علي آل صالح",
    "national_id": 1032829572,
    "phone": 555652441,
    "correspondence": "humoalsaleh",
    "email": "hmsalih@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "الموارد البشرية",
    "section": "عمليات الموارد البشرية",
    "unit": ""
  },
  {
    "id": 20157,
    "name": "حسين محمد عيسى الزباني",
    "national_id": 1062375660,
    "phone": 532073829,
    "correspondence": "humoalzabani",
    "email": "hzabani@momah.gov.sa",
    "job_title": "ميكانيكى",
    "department": "المشاريع والصحة العامة",
    "section": "الأزمات والطوارئ",
    "unit": ""
  },
  {
    "id": 2052,
    "name": "حمد أحمد محمد دوم",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "hdoum@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 5079,
    "name": "حمزه بن يحيى عبدالله الأمير",
    "national_id": 1039786575,
    "phone": 555044858,
    "correspondence": "",
    "email": "",
    "job_title": "مساعد مبرمج",
    "department": "التحول الرقمي",
    "section": "الخدمات الرقمية",
    "unit": ""
  },
  {
    "id": 201257,
    "name": "حيدر محمد الفضل حيدر النعمي",
    "national_id": 1029615984,
    "phone": 557568360,
    "correspondence": "hamoalnami",
    "email": "halnaamii@momah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 20159,
    "name": "خالد إبراهيم يحيى مشرقي",
    "national_id": 1034344646,
    "phone": 564278939,
    "correspondence": "khibmashreqi",
    "email": "kmashraqi@momah.gov.sa",
    "job_title": "مراقب نظافة",
    "department": "المشاريع والصحة العامة",
    "section": "صيانة الحدائق",
    "unit": ""
  },
  {
    "id": 20160,
    "name": "خالد أحمد حسن الحازمي",
    "national_id": 1072601873,
    "phone": 554369631,
    "correspondence": "khahalhazmi",
    "email": "kalhazimii@momah.gov.sa",
    "job_title": "كاتب",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 70005,
    "name": "خالد بن أحمد محمد عقيلي",
    "national_id": 1073555664,
    "phone": 538850378,
    "correspondence": "khahaqili",
    "email": "",
    "job_title": "بند الأجور",
    "department": "الشئون المالية",
    "section": "المشتريات",
    "unit": ""
  },
  {
    "id": 20161,
    "name": "خالد حمد حمود بشيري",
    "national_id": 1093866380,
    "phone": 565563140,
    "correspondence": "khhabashiri",
    "email": "kbashiri@momah.gov.sa",
    "job_title": "مراقب تعديات",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 20162,
    "name": "خالد علي يحيى عماري",
    "national_id": 1053200901,
    "phone": 509651362,
    "correspondence": "khalammari",
    "email": "khammari@momah.gov.sa",
    "job_title": "مساعد ادارى",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 201258,
    "name": "خالد قاسم أحمد فياض",
    "national_id": 1087013957,
    "phone": 538216117,
    "correspondence": "khqafayyad",
    "email": "khfayad@momah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20163,
    "name": "خالد كناني خليل طحاح",
    "national_id": 1054260060,
    "phone": 557977719,
    "correspondence": "khkntahah",
    "email": "khthah@momah.gov.sa",
    "job_title": "كاتب",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20164,
    "name": "خالد محمد احمد البر",
    "national_id": 1040647495,
    "phone": 538216117,
    "correspondence": "khmoalbr",
    "email": "khalbar@momah.gov.sa",
    "job_title": "ميكانيكى",
    "department": "المشاريع والصحة العامة",
    "section": "الأزمات والطوارئ",
    "unit": ""
  },
  {
    "id": 20165,
    "name": "درسي حسن محمد حيدري",
    "national_id": 1069148359,
    "phone": 538216117,
    "correspondence": "dahaheydari",
    "email": "dhaydri@momah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 201259,
    "name": "ربيع علي حسين شافعي",
    "national_id": 1048961104,
    "phone": 561868931,
    "correspondence": "raalshafei",
    "email": "rshafie@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 20166,
    "name": "رمزي محمد علي النعمي",
    "national_id": 1014837858,
    "phone": 559996217,
    "correspondence": "ramoalnaami",
    "email": "ralnamy@momah.gov.sa",
    "job_title": "مشرف خدمات",
    "department": "التخطيط العمراني والأراضي",
    "section": "الإراضي والتعديات",
    "unit": ""
  },
  {
    "id": 20167,
    "name": "زكريا إبراهيم محمد علامي",
    "national_id": 1078683040,
    "phone": 550318370,
    "correspondence": "zaiballami",
    "email": "zalami@momah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 20200,
    "name": "زكي عبدالفتاح محمد حشيبري",
    "national_id": 1096179500,
    "phone": 506767606,
    "correspondence": "zaafhsheabri",
    "email": "zhishbri@momah.gov.sa",
    "job_title": "مراقب صحى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 5007,
    "name": "زيلعي احمد علي صريحي",
    "national_id": 1024425314,
    "phone": 538216117,
    "correspondence": "zaahsarihi",
    "email": "zsraihi@momah.gov.sa",
    "job_title": "باحث قضايا",
    "department": "التخطيط العمراني والأراضي",
    "section": "نزع الملكية",
    "unit": ""
  },
  {
    "id": 201260,
    "name": "سامي علي جابر عسيري",
    "national_id": 1083890879,
    "phone": 558480858,
    "correspondence": "sgaseeri",
    "email": "sgaseeri@momah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20172,
    "name": "سلطان ادريس علي عسيري",
    "national_id": 1008357442,
    "phone": 566779894,
    "correspondence": "suidasiri",
    "email": "siaseeri@momah.gov.sa",
    "job_title": "مراقب انشاءات",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 20173,
    "name": "سلطان حسن علي موكلي",
    "national_id": 1073050278,
    "phone": 554644129,
    "correspondence": "suhamowkkli",
    "email": "smokali@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "المشاريع والصحة العامة",
    "section": "صيانة الحدائق",
    "unit": ""
  },
  {
    "id": 20174,
    "name": "سلطان علي عمر سعيد بارزيق",
    "national_id": 1053717763,
    "phone": 532322886,
    "correspondence": "sualbarzeeq",
    "email": "sbarziq@momah.gov.sa",
    "job_title": "مراقب خدمات",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20175,
    "name": "سلطان علي محمد الحازمي",
    "national_id": 1059029189,
    "phone": 531307175,
    "correspondence": "sualalhazmi",
    "email": "salhazimi@momah.gov.sa",
    "job_title": "مساح",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 20176,
    "name": "سلطان موسى حسن موكلي",
    "national_id": 1078604541,
    "phone": 552398218,
    "correspondence": "sumomowkkli",
    "email": "smokali@momah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "المشاريع والصحة العامة",
    "section": "صيانة الحدائق",
    "unit": ""
  },
  {
    "id": 2020,
    "name": "سمر عبد الله أحمد حكمي",
    "national_id": 1078114624,
    "phone": 551361714,
    "correspondence": "saabhakami",
    "email": "shakami@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20179,
    "name": "شعبين حسن هادي محمد",
    "national_id": 1112998040,
    "phone": 550703218,
    "correspondence": "shhamohmed",
    "email": "shmohammad@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "صحة البيئة",
    "unit": ""
  },
  {
    "id": 20180,
    "name": "صالح محمد احمد بكري",
    "national_id": 1078670187,
    "phone": 509484818,
    "correspondence": "samobakri",
    "email": "sbakri@momah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 20182,
    "name": "صلاح ماطر احمد صلاح",
    "national_id": 1018190759,
    "phone": 543444799,
    "correspondence": "samasalah",
    "email": "ssalah@momah.gov.sa",
    "job_title": "فنى زراعى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "تحسين المشهد الحضري",
    "unit": ""
  },
  {
    "id": 20183,
    "name": "ضحوي حمد حمود بشيري",
    "national_id": 1073286336,
    "phone": 553058057,
    "correspondence": "dahabashiri",
    "email": "dbashiri@momah.gov.sa",
    "job_title": "مراقب عمال",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 20184,
    "name": "طارق إبراهيم علي بركات",
    "national_id": 1015010802,
    "phone": 537026839,
    "correspondence": "taibbrkat",
    "email": "tbrakat@momah.gov.sa",
    "job_title": "فنى زراعى مشرف",
    "department": "المشاريع والصحة العامة",
    "section": "صيانة الحدائق",
    "unit": ""
  },
  {
    "id": 20185,
    "name": "طاهر محمد شوعي مباركي",
    "national_id": 1060464151,
    "phone": 507346706,
    "correspondence": "tamomubaraki",
    "email": "tmubarki@momah.gov.sa",
    "job_title": "مشرف نظافة",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20187,
    "name": "عادل أحمد علي شيخ",
    "national_id": 1071734576,
    "phone": 559615547,
    "correspondence": "adahsheikh",
    "email": "ashiekh@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "شؤون الموتي",
    "unit": ""
  },
  {
    "id": 20190,
    "name": "عباس علي محمد ياسين",
    "national_id": 1061673800,
    "phone": 569991324,
    "correspondence": "abalyaseen",
    "email": "ayaseen@momah.gov.sa",
    "job_title": "كاتب",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20201,
    "name": "عبدالرحمن احمد جابر عطيف",
    "national_id": 1076428802,
    "phone": 552300902,
    "correspondence": "abahatif",
    "email": "agotaif@momah.gov.sa",
    "job_title": "مهندس مدنى",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 2048,
    "name": "عبدالرحمن علي حمود الأعجم",
    "national_id": 1082751643,
    "phone": 530569229,
    "correspondence": "aalagam",
    "email": "aalagam@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201199,
    "name": "عبدالرحمن علي يحيى جربان",
    "national_id": 1072079153,
    "phone": 506464350,
    "correspondence": "moaljarban",
    "email": "mgarban@momah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 201109,
    "name": "عبدالعزيز أحمد يحيى شار صعدي",
    "national_id": 1041049790,
    "phone": 500409810,
    "correspondence": "abahsadi",
    "email": "ashar@momah.gov.sa",
    "job_title": "مراقب شئون الموظفين",
    "department": "الشؤون القانونية",
    "section": "المرافعات",
    "unit": ""
  },
  {
    "id": 70004,
    "name": "عبدالعزيز علي مهدي حمراني",
    "national_id": 1075581502,
    "phone": 533399202,
    "correspondence": "aahamrani",
    "email": "aahamrani@momah.gov.sa",
    "job_title": "مستخدم",
    "department": "العلاقات العامة والمشاركة المجتمعية",
    "section": "العلاقات العامة",
    "unit": ""
  },
  {
    "id": 20194,
    "name": "عبدالغني محمد يحيى زبيدي",
    "national_id": 1032710459,
    "phone": 506589732,
    "correspondence": "abmozubaidi",
    "email": "azabidi@momah.gov.sa",
    "job_title": "مراقب صحى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20195,
    "name": "عبداللطيف عيسى هادي أبو هادي",
    "national_id": 1079435697,
    "phone": 536768010,
    "correspondence": "abisabuhadi",
    "email": "aehadi@momah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 20197,
    "name": "عبدالله إبراهيم محمد جبرة",
    "national_id": 1041650696,
    "phone": 502692767,
    "correspondence": "abibjabrah",
    "email": "agabra@momah.gov.sa",
    "job_title": "كاتب",
    "department": "الموارد البشرية",
    "section": "تطوير الموارد البشرية",
    "unit": ""
  },
  {
    "id": 20198,
    "name": "عبدالله سرحان زين ذياب",
    "national_id": 1074265297,
    "phone": 550607369,
    "correspondence": "absathiab",
    "email": "azyab@momah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 20199,
    "name": "عبدالله عبده عبدالله عقيلي",
    "national_id": 1051458360,
    "phone": 500922312,
    "correspondence": "ababageeli",
    "email": "aaaqily@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "الموارد البشرية",
    "section": "عمليات الموارد البشرية",
    "unit": ""
  },
  {
    "id": 201101,
    "name": "عبدالله علي جابر قرادي حسابي",
    "national_id": 1054240518,
    "phone": 538216117,
    "correspondence": "abalhesabi",
    "email": "ahisabi@momah.gov.sa",
    "job_title": "بند الأجور",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 201102,
    "name": "عبدالله علي عبدالرحيم آل أحمد",
    "national_id": 1055680365,
    "phone": 559666738,
    "correspondence": "abalalahmed",
    "email": "aaahmedi@momah.gov.sa",
    "job_title": "مشرف أسواق",
    "department": "مكتب رئيس البلدية",
    "section": "مكتب رئيس اليلدية",
    "unit": ""
  },
  {
    "id": 201103,
    "name": "عبدالله علي محمد سلطان",
    "national_id": 1064625120,
    "phone": 534770472,
    "correspondence": "ahaisultan",
    "email": "asultan@momrah.gov.sa",
    "job_title": "مشرف أسواق",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "الرقاية الصحية",
    "unit": ""
  },
  {
    "id": 201104,
    "name": "عبدالله علي يحيى عماري",
    "national_id": 1053200919,
    "phone": 504666212,
    "correspondence": "abalamari",
    "email": "aamari@momrah.gov.sa",
    "job_title": "كاتب",
    "department": "الشؤون المالية",
    "section": "قسم التحصيل",
    "unit": ""
  },
  {
    "id": 5012,
    "name": "عبدالله محرق بوكر زيلعي",
    "national_id": 1066425586,
    "phone": 538216117,
    "correspondence": "",
    "email": "abzailaey@momrah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 201105,
    "name": "عبدالله محمد شامي العطار",
    "national_id": 1080780693,
    "phone": 559385614,
    "correspondence": "abmoalatar",
    "email": "aalataar@momrah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201106,
    "name": "عبدالله محمد علي العزي",
    "national_id": 1066523174,
    "phone": 557868946,
    "correspondence": "abmoalezi",
    "email": "aalezzi@momrah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 201211,
    "name": "عبدالهادي محمد احمد خواجي",
    "national_id": 1038683239,
    "phone": 569111905,
    "correspondence": "himdkhawaji",
    "email": "hkhawaji@momrah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "المراجعة الداخلية",
    "section": "فحص الشكاوي",
    "unit": ""
  },
  {
    "id": 20192,
    "name": "عبدالوهاب محمد احمد مجلي",
    "national_id": 1069706693,
    "phone": 557686778,
    "correspondence": "abmomojali",
    "email": "amagly@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 201108,
    "name": "عبده ادريس حسن ادريسي",
    "national_id": 1053355952,
    "phone": 501052235,
    "correspondence": "abededreesi",
    "email": "aidries@momrah.gov.sa",
    "job_title": "مراقب انشاءات",
    "department": "التخصيص والإستدامة المالية",
    "section": "الفرص الإستثمارية",
    "unit": ""
  },
  {
    "id": 201110,
    "name": "عبده علي محمد سلطان",
    "national_id": 1064487448,
    "phone": 504572836,
    "correspondence": "abalsultan",
    "email": "amsultan@momrah.gov.sa",
    "job_title": "اخصائي تقنية هندسة ميكانيكية ممارس",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 201111,
    "name": "عبده علي يحيى شامي",
    "national_id": 1056115056,
    "phone": 557865852,
    "correspondence": "abalshami",
    "email": "ashami@momrah.gov.sa",
    "job_title": "مساعد ادارى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201113,
    "name": "عبده هادي حسن حربوش",
    "national_id": 1041187921,
    "phone": 533626340,
    "correspondence": "abhaharbosh",
    "email": "aharbosh@momrah.gov.sa",
    "job_title": "محصل ايرادات",
    "department": "الشؤون المالية",
    "section": "قسم التحصيل",
    "unit": ""
  },
  {
    "id": 201114,
    "name": "عبده يحيى أحمد عبدالله",
    "national_id": 1069597803,
    "phone": 507823390,
    "correspondence": "abyaabdualla",
    "email": "ayahmed@momrah.gov.sa",
    "job_title": "كاتب",
    "department": "الشؤون المالية",
    "section": "المالية والميزانية",
    "unit": ""
  },
  {
    "id": 201115,
    "name": "عدنان علي شوعي العطار",
    "national_id": 1066601244,
    "phone": 507009193,
    "correspondence": "adalalatar",
    "email": "asalatar@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "شؤون الموتي",
    "unit": ""
  },
  {
    "id": 201116,
    "name": "عسيري عبدالله احمد النعمي",
    "national_id": 1017500446,
    "phone": 548626337,
    "correspondence": "asabalnami",
    "email": "aalnaamy@momrah.gov.sa",
    "job_title": "كاتب",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 201117,
    "name": "عطية ابراهيم محجوب قديمي",
    "national_id": 1065226092,
    "phone": 553531996,
    "correspondence": "atibqdemi",
    "email": "aqadimi@momrah.gov.sa",
    "job_title": "مساح",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 201119,
    "name": "علوي محمد أحمد القبي",
    "national_id": 1071807927,
    "phone": 535968147,
    "correspondence": "almoalgobi",
    "email": "aalqobi@momrah.gov.sa",
    "job_title": "كاتب",
    "department": "المشاريع والصحة العامة",
    "section": "صيانة الحدائق",
    "unit": ""
  },
  {
    "id": 201121,
    "name": "علي إدريس حسين ذبالي",
    "national_id": 1040233098,
    "phone": 508890713,
    "correspondence": "aledthebali",
    "email": "azbali@momrah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 5119,
    "name": "علي أحمد محمد النعمي",
    "national_id": 1020035828,
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "ميكانيكي سيارات",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 201122,
    "name": "علي أحمد محمد زارع",
    "national_id": 1063212110,
    "phone": 500251874,
    "correspondence": "alahzarea",
    "email": "azareh@momrah.gov.sa",
    "job_title": "مستخدم",
    "department": "التخطيط العمراني والأراضي",
    "section": "التخطيط العمراني والمساحة",
    "unit": ""
  },
  {
    "id": 5095,
    "name": "علي بن حسن بن حسن معبوج",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "مراقب انشاءات",
    "department": "التخصيص والإستدامة المالية",
    "section": "الفرص الإستثمارية",
    "unit": ""
  },
  {
    "id": 20222,
    "name": "علي بن حسين ابراهيم ابوخيرين",
    "national_id": 1062893589,
    "phone": 555339886,
    "correspondence": "alhuabukeriyn",
    "email": "",
    "job_title": "رئيس مراقبين صحيين",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20221,
    "name": "علي بن عبدالله بن علي مناع",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "ميكانيكى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 201123,
    "name": "علي حسن إبراهيم الحازمي",
    "national_id": 1025870369,
    "phone": 557277708,
    "correspondence": "aihnalhazmi",
    "email": "aalhazimi@momrah.gov.sa",
    "job_title": "مساعد ادارى",
    "department": "المشاريع والصحة العامة",
    "section": "النظافة",
    "unit": ""
  },
  {
    "id": 201124,
    "name": "علي حسن حسين غالبي",
    "national_id": 1034670271,
    "phone": 538216117,
    "correspondence": "alhaghalbi",
    "email": "ahgalibi@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 201127,
    "name": "علي حمود يحي حلواني",
    "national_id": 1055155087,
    "phone": 500348108,
    "correspondence": "alzyhalwani",
    "email": "ahalwani@momrah.gov.sa",
    "job_title": "مشرف خدمات",
    "department": "التخصيص والإستدامة المالية",
    "section": "الفرص الإستثمارية",
    "unit": ""
  },
  {
    "id": 201128,
    "name": "علي ذياب حسين عياشي",
    "national_id": 1022629297,
    "phone": 509381504,
    "correspondence": "alzyayashi",
    "email": "azayashi@momrah.gov.sa",
    "job_title": "مساح",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 201269,
    "name": "علي طميحي أحمد آل سريع",
    "national_id": 1051201158,
    "phone": 566699495,
    "correspondence": "altualsareea",
    "email": "asariea@momrah.gov.sa",
    "job_title": "مطور برامج أول",
    "department": "الموارد البشرية",
    "section": "الإتصالات الإدارية",
    "unit": ""
  },
  {
    "id": 201129,
    "name": "علي محمد أحمد مجلي",
    "national_id": 1069685582,
    "phone": 505788705,
    "correspondence": "almomojali",
    "email": "amojali@momrah.gov.sa",
    "job_title": "مدير الشؤون المالية",
    "department": "الشئون المالية",
    "section": "الشئون المالية",
    "unit": ""
  },
  {
    "id": 201131,
    "name": "علي محمد يحيى جبران",
    "national_id": 1026080331,
    "phone": 538216117,
    "correspondence": "almojobran",
    "email": "aygobran@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 201133,
    "name": "علي ناصر ابراهيم الذروي",
    "national_id": 1018695575,
    "phone": 173464962,
    "correspondence": "alnaalthrwi",
    "email": "azerwi@momrah.gov.sa",
    "job_title": "ميكانيكى",
    "department": "المشاريع والصحة العامة",
    "section": "الأزمات والطوارئ",
    "unit": ""
  },
  {
    "id": 201134,
    "name": "علي ناصر أحمد شبعاني",
    "national_id": 1047591431,
    "phone": 548658387,
    "correspondence": "alnashabani",
    "email": "ashbaani@momrah.gov.sa",
    "job_title": "مشرف خدمات",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201136,
    "name": "علي يحي احمد علاجي",
    "national_id": 1070573710,
    "phone": 538216117,
    "correspondence": "alyaalaji",
    "email": "aallagi@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 201137,
    "name": "علي يحيى احمد معافا",
    "national_id": 1074126283,
    "phone": 568175686,
    "correspondence": "alyamoafa",
    "email": "aymaafa@momrah.gov.sa",
    "job_title": "مراقب صحى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20206,
    "name": "عماد علي يحي درويش",
    "national_id": 1065817965,
    "phone": 532005144,
    "correspondence": "emaldarwish",
    "email": "edarwishi@momrah.gov.sa",
    "job_title": "فنى زراعى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "تحسين المشهد الحضري",
    "unit": ""
  },
  {
    "id": 201138,
    "name": "عمر عبده شوعي محوري",
    "national_id": 1016635375,
    "phone": 555969378,
    "correspondence": "omabmuhwari",
    "email": "omahwri@momrah.gov.sa",
    "job_title": "مراقب",
    "department": "التخطيط العمراني والأراضي",
    "section": "التخطيط العمراني والمساحة",
    "unit": ""
  },
  {
    "id": 201139,
    "name": "عمر علي حسن مخشوش",
    "national_id": 1065820449,
    "phone": 556767773,
    "correspondence": "omalmaqshosh",
    "email": "omakhshosh@momrah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "المشاريع والصحة العامة",
    "section": "النظافة",
    "unit": ""
  },
  {
    "id": 201140,
    "name": "عمر موسى محمد عكام",
    "national_id": 1035506318,
    "phone": 538216117,
    "correspondence": "ommoakam",
    "email": "oakkam@momrah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201142,
    "name": "عوني حسن علي غربي عبادي",
    "national_id": 1040863340,
    "phone": 541456544,
    "correspondence": "awhaabbadi",
    "email": "aabbadi@momrah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 5046,
    "name": "عيسى احمد موسى خرمي",
    "national_id": 1062997745,
    "phone": 507170368,
    "correspondence": "isahkhorrami",
    "email": "ekhormi@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "مكتب رئيس البلدية",
    "section": "مكتب رئيس اليلدية",
    "unit": ""
  },
  {
    "id": 201143,
    "name": "عيسى أبوهيبه احمد صريحي",
    "national_id": 1034811933,
    "phone": 544549161,
    "correspondence": "isabsarihi",
    "email": "ehares@momrah.gov.sa",
    "job_title": "فنى زراعى",
    "department": "المشاريع والصحة العامة",
    "section": "صيانة الحدائق",
    "unit": ""
  },
  {
    "id": 201144,
    "name": "عيسى علي حسن خواجي",
    "national_id": 1056611799,
    "phone": 538216117,
    "correspondence": "isalkwaji",
    "email": "ikhawagi@momrah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 201145,
    "name": "فتحي محمد احمد عربي",
    "national_id": 1021782055,
    "phone": 551366081,
    "correspondence": "famoarabi",
    "email": "farabi@momrah.gov.sa",
    "job_title": "مراقب انشاءات",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 201147,
    "name": "فهد حسن علي الذروي",
    "national_id": 1069639068,
    "phone": 547426053,
    "correspondence": "",
    "email": "falzerwi@momrah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201148,
    "name": "فهد حسن علي موكلي",
    "national_id": 1050743341,
    "phone": 559072415,
    "correspondence": "fahamokli",
    "email": "fhmokali@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "المشاريع والصحة العامة",
    "section": "صيانة الحدائق",
    "unit": ""
  },
  {
    "id": 201149,
    "name": "فهد عبده علي دحلان",
    "national_id": 1082179092,
    "phone": 557760555,
    "correspondence": "faabdahlan",
    "email": "fdahlan@momrah.gov.sa",
    "job_title": "مدقق حسابات",
    "department": "التخصيص والإستدامة المالية",
    "section": "الفرص الإستثمارية",
    "unit": ""
  },
  {
    "id": 201151,
    "name": "فهد محمد موسى معافا",
    "national_id": 1070277114,
    "phone": 505770437,
    "correspondence": "fdmdmoafa",
    "email": "fmaafa@momrah.gov.sa",
    "job_title": "محصل ايرادات",
    "department": "التخطيط العمراني والأراضي",
    "section": "الإراضي والتعديات",
    "unit": ""
  },
  {
    "id": 201146,
    "name": "فهد هادي محمد ضبياني",
    "national_id": 1050814985,
    "phone": 552152040,
    "correspondence": "fahadubyani",
    "email": "fdibyani@momrah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "المشاريع والصحة العامة",
    "section": "الطرق",
    "unit": ""
  },
  {
    "id": 201152,
    "name": "فواز محمد ابراهيم عطيف",
    "national_id": 1073910521,
    "phone": 555788675,
    "correspondence": "famoateef",
    "email": "fotaif@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 201153,
    "name": "فيصل محمد احمد البناء",
    "national_id": 1027298494,
    "phone": 551662665,
    "correspondence": "famoalbnaa",
    "email": "falbana@momrah.gov.sa",
    "job_title": "كاتب",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201154,
    "name": "فيصل محمد احمد معافا",
    "national_id": 1082077585,
    "phone": 557833126,
    "correspondence": "famomoafa",
    "email": "fmafa@momrah.gov.sa",
    "job_title": "فنى زراعى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "تحسين المشهد الحضري",
    "unit": ""
  },
  {
    "id": 201156,
    "name": "قاسم عبده اسماعيل سبعي",
    "national_id": 1094847181,
    "phone": 534757577,
    "correspondence": "qaabsabei",
    "email": "qsabai@momrah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "العلاقات العامة والمشاركة المجتمعية",
    "section": "العلاقات العامة",
    "unit": ""
  },
  {
    "id": 201157,
    "name": "كمال محمد عبده جميمي",
    "national_id": 1066625763,
    "phone": 533373543,
    "correspondence": "kamojmemi",
    "email": "kgamimi@momrah.gov.sa",
    "job_title": "فني صيانة آلات ميكانيكية",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 201160,
    "name": "ماجد محمد احمد قميري",
    "national_id": 1069305520,
    "phone": 538216117,
    "correspondence": "",
    "email": "mqimairi@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 201158,
    "name": "ماجد محمد احمد نهاري",
    "national_id": 1071664484,
    "phone": 593393439,
    "correspondence": "mamonahari",
    "email": "mnahari@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 201161,
    "name": "محسن إبراهيم محمد فقيه",
    "national_id": 1072145400,
    "phone": 502712008,
    "correspondence": "moibfageeh",
    "email": "mifaqih@momrah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 5117,
    "name": "محسن أحمد علي عداوي",
    "national_id": 1016278002,
    "phone": 552803309,
    "correspondence": "moahaddawi",
    "email": "madawi@momrah.gov.sa",
    "job_title": "مصمم برامج",
    "department": "التحول الرقمي",
    "section": "الخدمات الرقمية",
    "unit": ""
  },
  {
    "id": 5080,
    "name": "محسن بن علي أحمد خواجي",
    "national_id": 1089518607,
    "phone": 502634649,
    "correspondence": "",
    "email": "mkhawagi@momrah.gov.sa",
    "job_title": "ناسخ أله",
    "department": "التخصيص والإستدامة المالية",
    "section": "الفرص الإستثمارية",
    "unit": ""
  },
  {
    "id": 201162,
    "name": "محطلم محمد عيسى البناء",
    "national_id": 1062650872,
    "phone": 550344953,
    "correspondence": "mumoalbnaa",
    "email": "malbnaa@momrah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 20225,
    "name": "محمد ابراهيم محسن عطيف",
    "national_id": 1028686036,
    "phone": 541188981,
    "correspondence": "moibautef",
    "email": "",
    "job_title": "مساح",
    "department": "التخصيص والإستدامة المالية",
    "section": "التخصيص والإستدامة المالية",
    "unit": ""
  },
  {
    "id": 5041,
    "name": "محمد احمد دلاك بقاشي",
    "national_id": 1059863520,
    "phone": 501020399,
    "correspondence": "moahdaillak",
    "email": "mbqashi@momrah.gov.sa",
    "job_title": "مسجل معلومات",
    "department": "مكتب رئيس البلدية",
    "section": "مكتب رئيس اليلدية",
    "unit": ""
  },
  {
    "id": 5040,
    "name": "محمد احمد محمد سبعي",
    "national_id": 1016851865,
    "phone": 502333090,
    "correspondence": "moahsaabey",
    "email": "msabie@momrah.gov.sa",
    "job_title": "اخصائي عمليات موارد بشرية",
    "department": "التخصيص والإستدامة المالية",
    "section": "الفرص الإستثمارية",
    "unit": ""
  },
  {
    "id": 2023,
    "name": "محمد العابد محمد حيدر النعمي",
    "national_id": 1052696661,
    "phone": 533442246,
    "correspondence": "moalalnemi",
    "email": "mhalnami@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "المشاريع والصحة العامة",
    "section": "الأزمات والطوارئ",
    "unit": ""
  },
  {
    "id": 201165,
    "name": "محمد إبراهيم حاشد راجحي",
    "national_id": 1048219958,
    "phone": 538216117,
    "correspondence": "",
    "email": "mrajihi@momrah.gov.sa",
    "job_title": "كهربائى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 201166,
    "name": "محمد إسماعيل يحي طواشي",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "بند الأجور",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 201167,
    "name": "محمد أحمد حسن الحازمي",
    "national_id": 1072474982,
    "phone": 560005497,
    "correspondence": "mdadalhazmi",
    "email": "malhazimi@momrah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "صحة البيئة",
    "unit": ""
  },
  {
    "id": 201168,
    "name": "محمد أحمديني احمد الجلبي",
    "national_id": 1066256544,
    "phone": 537872339,
    "correspondence": "moahaljalabi",
    "email": "malgalbi@momrah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 5039,
    "name": "محمد بن محسن موسى خرمي",
    "national_id": 1022018285,
    "phone": 553886972,
    "correspondence": "momokharmi",
    "email": "mkhormi@momrah.gov.sa",
    "job_title": "رئيس بلدية صبيا",
    "department": "رئيس بلدية محافظة صبيا",
    "section": "رئيس بلدية محافظة صبيا",
    "unit": ""
  },
  {
    "id": 201170,
    "name": "محمد جيلان علي نجعي",
    "national_id": 1069958542,
    "phone": 558865519,
    "correspondence": "mojenajey",
    "email": "mnagaai@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201171,
    "name": "محمد حسن احمد حقوي",
    "national_id": 1056612888,
    "phone": 538216117,
    "correspondence": "mohahaqawy",
    "email": "mhaqawy@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 20213,
    "name": "محمد حسن خليل طاهري",
    "national_id": 1052467386,
    "phone": 531128547,
    "correspondence": "mohatahiri",
    "email": "mtahiri@momrah.gov.sa",
    "job_title": "طبيب بيطرى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201173,
    "name": "محمد حسين حسن شولان",
    "national_id": 1047679160,
    "phone": 553099559,
    "correspondence": "moheshwlan",
    "email": "mshawlan@momrah.gov.sa",
    "job_title": "رئيس مراقبين صحيين",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201172,
    "name": "محمد حسين حمود ظبيع",
    "national_id": 1078380183,
    "phone": 505706764,
    "correspondence": "mohedabie",
    "email": "mdibaia@momrah.gov.sa",
    "job_title": "كاتب",
    "department": "الموارد البشرية",
    "section": "الإتصالات الإدارية",
    "unit": ""
  },
  {
    "id": 2028,
    "name": "محمد حمود علي جبلي",
    "national_id": 1088564123,
    "phone": 530777894,
    "correspondence": "mohajabli",
    "email": "mgabli@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 5098,
    "name": "محمد سالم أحمد خواجي",
    "national_id": "",
    "phone": 544972722,
    "correspondence": "mosakhawaji",
    "email": "mkhawaje@momrah.gov.sa",
    "job_title": "اخصائى شؤون موظفين",
    "department": "الموارد البشرية",
    "section": "تطوير الموارد البشرية",
    "unit": ""
  },
  {
    "id": 201176,
    "name": "محمد طالع سالم عابدين",
    "national_id": 1073378042,
    "phone": 501414110,
    "correspondence": "motaabdeen",
    "email": "mtabdin@momrah.gov.sa",
    "job_title": "كاتب",
    "department": "الموارد البشرية",
    "section": "عمليات الموارد البشرية",
    "unit": ""
  },
  {
    "id": 201177,
    "name": "محمد عبدالله سويد عامري",
    "national_id": 1059095198,
    "phone": 557717747,
    "correspondence": "moabamri",
    "email": "mameeri@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "شؤون الموتي",
    "unit": ""
  },
  {
    "id": 201178,
    "name": "محمد عبده محمد غزاوي",
    "national_id": 1038197800,
    "phone": 557799553,
    "correspondence": "moabgazwi",
    "email": "mgazawyi@momrah.gov.sa",
    "job_title": "كاتب",
    "department": "المراجعة الداخلية",
    "section": "فحص الشكاوي",
    "unit": ""
  },
  {
    "id": 201279,
    "name": "محمد عثمان عيسى مده",
    "national_id": 1088436843,
    "phone": 555656442,
    "correspondence": "moosmadah",
    "email": "mmadah@momrah.gov.sa",
    "job_title": "كاتب",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 201261,
    "name": "محمد علي إبراهيم خليل مطهري",
    "national_id": 1069356549,
    "phone": 502400933,
    "correspondence": "moalmotahari",
    "email": "mmathari@momrah.gov.sa",
    "job_title": "مراقب عمال",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 201180,
    "name": "محمد علي أحمد عبدالله مجلي",
    "national_id": 1065247791,
    "phone": 536018422,
    "correspondence": "moalmejali",
    "email": "mmagli@momrah.gov.sa",
    "job_title": "سكرتير لجنه",
    "department": "الشئون المالية",
    "section": "المستودعات",
    "unit": ""
  },
  {
    "id": 201181,
    "name": "محمد علي حسن هادي",
    "national_id": 1103789895,
    "phone": 502271536,
    "correspondence": "moalhadi",
    "email": "mmakhshosh@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201182,
    "name": "محمد علي علي دربشي",
    "national_id": 1057500967,
    "phone": 559190478,
    "correspondence": "moalderbshi",
    "email": "mdarbshii@momrah.gov.sa",
    "job_title": "مسجل معلومات",
    "department": "المراجعة الداخلية",
    "section": "المراجعة الداخلية",
    "unit": ""
  },
  {
    "id": 201183,
    "name": "محمد علي محمد أبوعليطة",
    "national_id": 1064724105,
    "phone": 538216117,
    "correspondence": "moalabualeta",
    "email": "melaita@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 201184,
    "name": "محمد علي محمد عقيلي",
    "national_id": 1090233840,
    "phone": 553773261,
    "correspondence": "moalaqeli",
    "email": "maaqili@momrah.gov.sa",
    "job_title": "مساعد ادارى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20209,
    "name": "محمد محسن حسين مجدوع",
    "national_id": 1049933466,
    "phone": 557999294,
    "correspondence": "momomagdoa",
    "email": "mmagdoh@momrah.gov.sa",
    "job_title": "مساح",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 201186,
    "name": "محمد مريش حسن الخياط",
    "national_id": 1084027281,
    "phone": 506767007,
    "correspondence": "momualkhiat",
    "email": "malkhayat@momrah.gov.sa",
    "job_title": "مساعد ادارى",
    "department": "التخطيط العمراني والأراضي",
    "section": "التخطيط العمراني والمساحة",
    "unit": ""
  },
  {
    "id": 201188,
    "name": "محمد موسى عيسى غزاوي",
    "national_id": 1047669716,
    "phone": 540377366,
    "correspondence": "momoghazzawi",
    "email": "mgazawi@momrah.gov.sa",
    "job_title": "مدير مشتريات",
    "department": "الشئون المالية",
    "section": "المشتريات",
    "unit": ""
  },
  {
    "id": 201189,
    "name": "محمد موسى غالب وشيلي",
    "national_id": 1068747466,
    "phone": 533884123,
    "correspondence": "momowsheli",
    "email": "mwashili@momrah.gov.sa",
    "job_title": "ميكانيكى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 201190,
    "name": "محمد ناصر حيان ميالي",
    "national_id": 1092936598,
    "phone": 557546947,
    "correspondence": "monamiali",
    "email": "mmaialir@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "صحة البيئة",
    "unit": ""
  },
  {
    "id": 5004,
    "name": "محمد يحي احمد الامير",
    "national_id": 1041613645,
    "phone": 537330030,
    "correspondence": "mdyaalameer",
    "email": "malamir@momrah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201192,
    "name": "مساعد حمدان احمد العاتي",
    "national_id": 1020329338,
    "phone": 503773616,
    "correspondence": "mohaalati",
    "email": "malaati@momrah.gov.sa",
    "job_title": "فنى زراعى",
    "department": "المشاريع والصحة العامة",
    "section": "صيانة الحدائق",
    "unit": ""
  },
  {
    "id": 201193,
    "name": "مسدف علي محمد الظيف",
    "national_id": 1064671314,
    "phone": 566999886,
    "correspondence": "moalaldayf",
    "email": "malzaif@momrah.gov.sa",
    "job_title": "مراقب عمال",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 201194,
    "name": "مصطفى محمد احمد سلطان",
    "national_id": 1085980850,
    "phone": 569982278,
    "correspondence": "momosultan",
    "email": "masultan@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التشغيل والصيانة",
    "unit": ""
  },
  {
    "id": 201195,
    "name": "مصطفى محمد علي الحمزي",
    "national_id": 1019341286,
    "phone": 531936697,
    "correspondence": "momoalhamzi",
    "email": "malhamzy@momrah.gov.sa",
    "job_title": "ميكانيكى سيارات",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 5011,
    "name": "مصعب ثابت عثمان حكمي",
    "national_id": 1075300317,
    "phone": 538216117,
    "correspondence": "mohakmi",
    "email": "mthakami@momrah.gov.sa",
    "job_title": "مسجل معلومات",
    "department": "التخطيط العمراني والأراضي",
    "section": "نزع الملكية",
    "unit": ""
  },
  {
    "id": 201197,
    "name": "مكي علي محمد غروي",
    "national_id": 1018215796,
    "phone": 550797901,
    "correspondence": "maalgarawi",
    "email": "mgarawi@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201198,
    "name": "مكي محمد إبراهيم قنوي",
    "national_id": 1064190943,
    "phone": 598059795,
    "correspondence": "mamoganwi",
    "email": "mgarban@momrah.gov.sa",
    "job_title": "مراقب عمال",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201265,
    "name": "منصور صالح سليمان شافعي",
    "national_id": 1023222688,
    "phone": 557873311,
    "correspondence": "masashafiei",
    "email": "mshaafie@momrah.gov.sa",
    "job_title": "رسام معمارى",
    "department": "التخطيط العمراني والأراضي",
    "section": "نزع الملكية",
    "unit": ""
  },
  {
    "id": 201200,
    "name": "منصور محمد العابد حيدر النعمي",
    "national_id": 1067374080,
    "phone": 551374589,
    "correspondence": "mamohedar",
    "email": "malnami@momrah.gov.sa",
    "job_title": "كهربائى",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 20202,
    "name": "منصور مفرح مانع المالكي",
    "national_id": 1049531773,
    "phone": 544979200,
    "correspondence": "mamoalmalki",
    "email": "mmalmaliki@momrah.gov.sa",
    "job_title": "مطور برامج مساعد",
    "department": "التحول الرقمي",
    "section": "الخدمات الرقمية",
    "unit": ""
  },
  {
    "id": 2049,
    "name": "مهدي محمد عيسى مناع",
    "national_id": 1103732549,
    "phone": 553324722,
    "correspondence": "mamomanna",
    "email": "mmnaa@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201201,
    "name": "موسى علي محمد النجعي",
    "national_id": 1062136922,
    "phone": 557335784,
    "correspondence": "moalalnajai",
    "email": "malnagai@momrah.gov.sa",
    "job_title": "مراقب انشاءات",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 201202,
    "name": "موسى يحي محمد الذروي",
    "national_id": 1050803764,
    "phone": 563057676,
    "correspondence": "maltherwi",
    "email": "myalerwi@momrah.gov.sa",
    "job_title": "مسجل معلومات",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201203,
    "name": "ناجي محمد حمود الحازمي",
    "national_id": 1058494095,
    "phone": 503099036,
    "correspondence": "namoalhazmi",
    "email": "nalhazmi@momrah.gov.sa",
    "job_title": "مصمم برامج",
    "department": "مساعد رئيس البلدية",
    "section": "مكتب مساعد الرئيس",
    "unit": ""
  },
  {
    "id": 201204,
    "name": "ناصر إسماعيل نبوت مبارك",
    "national_id": 1087847446,
    "phone": 501609064,
    "correspondence": "naesmobark",
    "email": "nimubark@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "شؤون الموتي",
    "unit": ""
  },
  {
    "id": 201205,
    "name": "ناصر حسن عبدالله ياسين",
    "national_id": 1037747399,
    "phone": 503110375,
    "correspondence": "nahayaseen",
    "email": "nyasien@momrah.gov.sa",
    "job_title": "مسجل معلومات",
    "department": "المشاريع والصحة العامة",
    "section": "النظافة",
    "unit": ""
  },
  {
    "id": 201206,
    "name": "ناصر حسن محمد الذروي",
    "national_id": 1055399834,
    "phone": 558558696,
    "correspondence": "nahaaltherwi",
    "email": "nhaltherwi@momrah.gov.sa",
    "job_title": "مطور برامج أول",
    "department": "التحول الرقمي",
    "section": "الخدمات الرقمية",
    "unit": ""
  },
  {
    "id": 201207,
    "name": "ناصر محمد احمد عامري",
    "national_id": 1029062583,
    "phone": 503035069,
    "correspondence": "namoamri",
    "email": "nameri@momrah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 5008,
    "name": "ناظر احمد عبدالله علي",
    "national_id": 1094680756,
    "phone": 536858410,
    "correspondence": "naahali",
    "email": "nali@momrah.gov.sa",
    "job_title": "مراقب عمال",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 2024,
    "name": "نايف موسى عبده تهامي",
    "national_id": 1129880553,
    "phone": 508306804,
    "correspondence": "namotahami",
    "email": "nmtohamy@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التحول الرقمي",
    "section": "الخدمات الرقمية",
    "unit": ""
  },
  {
    "id": 20210,
    "name": "نجود علي يحيى قاضي",
    "national_id": 1081883249,
    "phone": 540464134,
    "correspondence": "noalqadi",
    "email": "nqadi@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 2044,
    "name": "ندى احمد علي سهلي",
    "national_id": 1080874108,
    "phone": 538216117,
    "correspondence": "naahsehaili",
    "email": "nsahli@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201210,
    "name": "هادي أحمد محمد بشير معافا",
    "national_id": 1025369040,
    "phone": 538216117,
    "correspondence": "haahmoafa",
    "email": "hamoafa@momrah.gov.sa",
    "job_title": "مساعد ادارى",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 201212,
    "name": "هاشم طميحي احمد ال سريع",
    "national_id": 1051201182,
    "phone": 557157352,
    "correspondence": "hatoalsriia",
    "email": "hsareea@momrah.gov.sa",
    "job_title": "مراقب نظافة",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201213,
    "name": "هاشم علي محمد السبعي",
    "national_id": 1083663961,
    "phone": 551509031,
    "correspondence": "haalalsabai",
    "email": "halsabie@momrah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 201214,
    "name": "وائل علي حسن عبده هادي",
    "national_id": 1103789887,
    "phone": 598977481,
    "correspondence": "waalhadi",
    "email": "whadi@momrah.gov.sa",
    "job_title": "كاتب",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 201218,
    "name": "وليد يحيى احمد مشلوي",
    "national_id": 1080978313,
    "phone": 535376852,
    "correspondence": "wayamoshalwi",
    "email": "wmashlwi@momrah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "الموارد البشرية",
    "section": "الأمن والسلامة",
    "unit": ""
  },
  {
    "id": 201219,
    "name": "ياسر علي ضيف الله مريع",
    "national_id": 1055309460,
    "phone": 553788876,
    "correspondence": "yaalmuriea",
    "email": "ymriea@momrah.gov.sa",
    "job_title": "مهندس تخطيط",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 201220,
    "name": "يحيى احمد يحيى طيري",
    "national_id": 1088953763,
    "phone": 538216117,
    "correspondence": "yaahtari",
    "email": "ytayri@momrah.gov.sa",
    "job_title": "مراقب أمن وسلامه",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "شؤون الموتي",
    "unit": ""
  },
  {
    "id": 201221,
    "name": "يحيى حسن إبراهيم الحازمي",
    "national_id": 1025870385,
    "phone": 500341001,
    "correspondence": "yahaalhazmi",
    "email": "yalhazmi@momrah.gov.sa",
    "job_title": "كهربائى",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 201224,
    "name": "يحيى علي ناصر درموح",
    "national_id": 1045811542,
    "phone": 544441640,
    "correspondence": "yaaldarmoh",
    "email": "ydarmoh@momrah.gov.sa",
    "job_title": "مسجل معلومات",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 201225,
    "name": "يحيى علي يحيى باصهي",
    "national_id": 1068257292,
    "phone": 509434004,
    "correspondence": "yaalbasahi",
    "email": "ybasahi@momrah.gov.sa",
    "job_title": "مساعد ادارى",
    "department": "الموارد البشرية",
    "section": "عمليات الموارد البشرية",
    "unit": ""
  },
  {
    "id": 201226,
    "name": "يحيى علي يحيى عماري",
    "national_id": 1053200885,
    "phone": 553788899,
    "correspondence": "yaalammari",
    "email": "yamari@momrah.gov.sa",
    "job_title": "مساعد ادارى",
    "department": "المشاريع والصحة العامة",
    "section": "صيانة الحدائق",
    "unit": ""
  },
  {
    "id": 201227,
    "name": "يحيى ماطر ابراهيم خواجي",
    "national_id": 1065797464,
    "phone": 559430030,
    "correspondence": "yamakhawaji",
    "email": "ykhawaji@momrah.gov.sa",
    "job_title": "رئيس مراقبين صحيين",
    "department": "التراخيص والإمتثال وتحسين المشهد الحضري",
    "section": "التراخيص والإمتثال",
    "unit": ""
  },
  {
    "id": 201228,
    "name": "يحيى محمد احمد مجلي",
    "national_id": 1069685616,
    "phone": 551970998,
    "correspondence": "yemomegally",
    "email": "ymagli@momrah.gov.sa",
    "job_title": "مساعد ادارى",
    "department": "الشئون المالية",
    "section": "المالية والميزانية",
    "unit": ""
  },
  {
    "id": 201229,
    "name": "يحيى محمد أحمد قميري",
    "national_id": 1069305504,
    "phone": 549121046,
    "correspondence": "yamoqumairi",
    "email": "yqamiri@momrah.gov.sa",
    "job_title": "مراقب اسواق",
    "department": "المشاريع والصحة العامة",
    "section": "النظافة",
    "unit": ""
  },
  {
    "id": 201230,
    "name": "يحيى محمد يحيى شاطري",
    "national_id": 1058184506,
    "phone": 538793141,
    "correspondence": "yamoshatri",
    "email": "yshatri@momrah.gov.sa",
    "job_title": "مراقب انشاءات",
    "department": "التخطيط العمراني والأراضي",
    "section": "الرقابة الإنشائية والتراخيص",
    "unit": ""
  },
  {
    "id": 2046,
    "name": "يحيى محي محسن عميش",
    "national_id": 1074201011,
    "phone": 554927460,
    "correspondence": "yamuamish",
    "email": "yemaish@momrah.gov.sa",
    "job_title": "بند الأجور",
    "department": "المشاريع والصحة العامة",
    "section": "المشاريع",
    "unit": ""
  },
  {
    "id": 2039,
    "name": "امين ال اسلام حسين",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "عامل",
    "department": "المشاريع والصحة العامة",
    "section": "المرافق العامة",
    "unit": ""
  },
  {
    "id": 2034,
    "name": "بهادور مياه عبد الجليل",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "عامل",
    "department": "المشاريع والصحة العامة",
    "section": "المرافق العامة",
    "unit": ""
  },
  {
    "id": 2040,
    "name": "حبيب شاه جهان ميا",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "عامل",
    "department": "المشاريع والصحة العامة",
    "section": "المرافق العامة",
    "unit": ""
  },
  {
    "id": 2033,
    "name": "زاهد ال حسن عبده رشيد",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "عامل",
    "department": "المشاريع والصحة العامة",
    "section": "المرافق العامة",
    "unit": ""
  },
  {
    "id": 2037,
    "name": "سيف الاسلام عبد الملك",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "عامل",
    "department": "المشاريع والصحة العامة",
    "section": "المرافق العامة",
    "unit": ""
  },
  {
    "id": 2035,
    "name": "محمد افسر مياه",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "عامل",
    "department": "المشاريع والصحة العامة",
    "section": "المرافق العامة",
    "unit": ""
  },
  {
    "id": 2032,
    "name": "محمد جايدول ال اسلام",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "عامل",
    "department": "المشاريع والصحة العامة",
    "section": "المرافق العامة",
    "unit": ""
  },
  {
    "id": 2038,
    "name": "محمد راسل مبروك",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "عامل",
    "department": "المشاريع والصحة العامة",
    "section": "المرافق العامة",
    "unit": ""
  },
  {
    "id": 2041,
    "name": "محمد سيف ال اسلام",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "عامل",
    "department": "المشاريع والصحة العامة",
    "section": "المرافق العامة",
    "unit": ""
  },
  {
    "id": 5120,
    "name": "روان عبده محمد عقيلي",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "تمهير",
    "department": "إدارة التراخيص و الامتثال و تحسين المشهد الحضري",
    "section": "",
    "unit": ""
  },
  {
    "id": 5104,
    "name": "ايمان طاهر محمد مباركي",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "تمهير",
    "department": "إدارة التراخيص و الامتثال و تحسين المشهد الحضري",
    "section": "",
    "unit": ""
  },
  {
    "id": 5106,
    "name": "منال محمد طاهر بكيري عاتي",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "تمهير",
    "department": "إدارة التراخيص و الامتثال و تحسين المشهد الحضري",
    "section": "",
    "unit": ""
  },
  {
    "id": 5107,
    "name": "نهى علي محمد النعمي",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "تمهير",
    "department": "إدارة التراخيص و الامتثال و تحسين المشهد الحضري",
    "section": "",
    "unit": ""
  },
  {
    "id": 5108,
    "name": "أمة الرحمن ابراهيم حسن النعمي",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "تمهير",
    "department": "إدارة التراخيص و الامتثال و تحسين المشهد الحضري",
    "section": "",
    "unit": ""
  },
  {
    "id": 5109,
    "name": "مها محمد أحمد ذبالي",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "تمهير",
    "department": "إدارة التراخيص و الامتثال و تحسين المشهد الحضري",
    "section": "",
    "unit": ""
  },
  {
    "id": 5110,
    "name": "زمزم أحمد حمد مرير",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "تمهير",
    "department": "إدارة التراخيص و الامتثال و تحسين المشهد الحضري",
    "section": "",
    "unit": ""
  },
  {
    "id": 5111,
    "name": "هدى أحمد علي حاج",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "تمهير",
    "department": "إدارة التراخيص و الامتثال و تحسين المشهد الحضري",
    "section": "",
    "unit": ""
  },
  {
    "id": 5112,
    "name": "دارين مهدي صديق حكمي",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "تمهير",
    "department": "إدارة التراخيص و الامتثال و تحسين المشهد الحضري",
    "section": "",
    "unit": ""
  },
  {
    "id": 5113,
    "name": "دعاء عبده محمد قعاري",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "تمهير",
    "department": "إدارة التراخيص و الامتثال و تحسين المشهد الحضري",
    "section": "",
    "unit": ""
  },
  {
    "id": 5114,
    "name": "صالحه علي محمد حيان",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "تمهير",
    "department": "إدارة التراخيص و الامتثال و تحسين المشهد الحضري",
    "section": "",
    "unit": ""
  },
  {
    "id": 5115,
    "name": "عائشه غالب يحيى عريبي",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "تمهير",
    "department": "إدارة التراخيص و الامتثال و تحسين المشهد الحضري",
    "section": "",
    "unit": ""
  },
  {
    "id": 5116,
    "name": "شذى يحي ابراهيم القاصر",
    "national_id": "",
    "phone": "",
    "correspondence": "",
    "email": "",
    "job_title": "تمهير",
    "department": "إدارة التراخيص و الامتثال و تحسين المشهد الحضري",
    "section": "",
    "unit": ""
  }
];

